### ISSUE TITLE
crash on GET /level/1

### ISSUE THREAD

**Issue by rolandplanitz** [Creamfinance/clashing-coders-rpg#1]
Hi, I tried to set the server up on my machine (OS X 10.11.5).
I started a redis server `$ redis-server`
Then I started the server `$ node start.js`

I can authenticate against the API (with the user/pass data I set up in the psql db)
But when I call /level/1 it crashes:

```
Listening on : 8888
true
200 - POST /authenticate (req-5550a3c8739ea5c87db29a8ca9eb5a59, Queries (0, 0, 0, 0)) took 29.140154 ms
{ LEVEL_ID: '1' }
200 - GET /level/1 (req-634781a66c006f13f9a867d35aa83969, Queries (0, 0, 0, 0)) took 27.088951 ms
{ LEVEL_ID: '1' }
/Users/roland/git/clashing-coders-rpg/controllers/QuestController.js:174
        if (!(request.variables.LEVEL_ID in request.user.level_metadata) ||
                                                        ^

TypeError: Cannot use 'in' operator to search for '1' in undefined
    at constructor.handleStartLevel (/Users/roland/git/clashing-coders-rpg/controllers/QuestController.js:174:57)
    at callCallback (/Users/roland/git/clashing-coders-rpg/RestRoutingHandler.js:428:46)
    at handleResolver (/Users/roland/git/clashing-coders-rpg/RestRoutingHandler.js:416:33)
    at LevelResolver (/Users/roland/git/clashing-coders-rpg/resolvers/LevelResolver.js:39:13)
    at handleResolver (/Users/roland/git/clashing-coders-rpg/RestRoutingHandler.js:414:33)
    at Command.callback (/Users/roland/git/clashing-coders-rpg/resolvers/UserResolver.js:38:13)
    at normal_reply (/Users/roland/git/clashing-coders-rpg/node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/Users/roland/git/clashing-coders-rpg/node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.returnReply (/Users/roland/git/clashing-coders-rpg/node_modules/redis/index.js:188:18)
    at JavascriptRedisParser.execute (/Users/roland/git/clashing-coders-rpg/node_modules/redis/node_modules/redis-parser/lib/parser.js:415:12)
```

Is there something I sould do different?
I have never used node.js before, so I hope it is a simple problem.

Best regards
roland

**Comment by RianFuro** [comment]
Good catch!
I wonder how we didn't encounter that one during the contest though... 
Anyway, should work now if you pull the update :)
